name: deploy

on:
  push:
    branches:
      - master

jobs:

  versionist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run balena-versionist
      uses: tmigone/versionist@master
      with:
        github_email: 'tomasmigone@gmail.com'
        github_username: 'versionist'
        github_token: ${{ secrets.GH_ADMIN_TOKEN }}